services:
  the-database:
    image: mysql
    container_name: the-database

    env_file:
      - .env

    ports:
      - "3006:3006"

    restart: always

    networks:
      - the-network

    volumes: 
      - mysql-volume:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d

  the-api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3333:3333"

    env_file:
      - .env

    restart: always

    depends_on:
      - the-database

    networks:
      - the-network

volumes:
  mysql-volume:

networks:
  the-network:
    driver: bridge 