CREATE TABLE IF NOT EXISTS movies (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL UNIQUE,
  year YEAR NOT NULL,
  synopsis VARCHAR(255) NOT NULL,
  genres VARCHAR(100) NOT NULL,
  director VARCHAR(100) NOT NULL,
  actors VARCHAR(170) NOT NULL,

  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ratings (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  note SMALLINT NOT NULL,
  comment VARCHAR(255) NOT NULL,
  id_movie INT NOT NULL,

  PRIMARY KEY(id),
  FOREIGN KEY(id_movie) REFERENCES movies(id) ON DELETE CASCADE
)